#!/usr/bin/env bash
# installing a load balancer

# Update package repository
sudo apt update

# Install HAProxy
sudo apt install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null << EOF
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server web-01 34.232.66.200:80
    server web-02 54.234.82.27:80
EOF

# Enable HAProxy management via init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Start and enable HAProxy
sudo service haproxy start
sudo systemctl enable haproxy
